blueprint:
  name: Prego - Encender Bombilla con Brillo Incremental
  description: Enciende una bombilla e incrementa gradualmente su brillo hasta llegar al 40%.
  domain: automation
  input:
    in_light_entity:
      name: Entidad de la Bombilla
      description: La entidad de la bombilla que quieres encender.
      selector:
        entity:
          domain: light
    in_transition_duration:
      name: Duración de la Transición
      description: Duración en segundos para incrementar gradualmente el brillo.
      default: 60
      selector:
        number:
          min: 1
          max: 600
          unit_of_measurement: Seconds

trigger:
  - platform: state
    entity_id: !input in_light_entity
    to: 'on'

action:
  - repeat:
      sequence:
        - service: light.turn_on
          target:
            entity_id: !input in_light_entity
          data:
            brightness_pct: "{{ (loop.index * 40 / (states.input_number.in_transition_duration.state | int)) | round(0) }}"
        - delay: "{{ (states.input_number.in_transition_duration.state | int / 40) | round(0) }}"
      count: 40
