blueprint:
  name: Encender Bombilla con Brillo Personalizado
  description: Enciende una bombilla con un brillo personalizado.
  domain: automation
  input:
    light_entity:
      name: Entidad de la Bombilla
      description: La entidad de la bombilla que quieres encender.
      selector:
        entity:
          domain: light
    transition:
      name: Duración de la Transición (opcional)
      description: La duración en segundos de la transición al nuevo brillo (0 para cambio instantáneo).
      default: 0
      selector:
        number:
          min: 0
          max: 600
          mode: slider
          step: 1
          unit_of_measurement: Seconds

trigger:
  - platform: state
    entity_id: !input light_entity
    to: 'on'

action:
  - service: light.turn_on
    target:
      entity_id: !input light_entity
    data:
      brightness_pct: 40
      transition: !input transition
