blueprint:
  name: Encender Bombilla con Brillo Fijo
  description: Enciende una bombilla con un brillo fijo del 40%.
  domain: automation
  input:
    light_entity:
      name: Entidad de la Bombilla
      description: La entidad de la bombilla que quieres encender.
      selector:
        entity:
          domain: light

trigger:
  - platform: state
    entity_id: !input light_entity
    to: 'on'

action:
  - service: light.turn_on
    target:
      entity_id: !input light_entity
    data:
      brightness_pct: 40
