blueprint:
  name: Encender Bombilla con Brillo Incremental
  description: Enciende una bombilla e incrementa gradualmente su brillo hasta llegar al 40%.
  domain: automation
  input:
    in_light_entity:
      name: Entidad de la Bombilla
      description: La entidad de la bombilla que quieres encender.
      selector:
        entity:
          domain: light
    im_transition_duration:
      name: Duración de la Transición
      description: Duración en segundos para incrementar gradualmente el brillo.
      default: 60
      selector:
        number:
          min: 1
          max: 600
          unit_of_measurement: Seconds

trigger:
  - platform: state
    entity_id: !input in_light_entity
    to: 'on'

action:
  - service: light.turn_on
    target:
      entity_id: !input in_light_entity
    data:
      brightness_pct: 40
      transition: !input im_transition_duration
